# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='group',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='opposite',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
