# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20161227_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
